### ISSUE TITLE
README.md does not explain makefile

### ISSUE THREAD

**Issue by Sevensidedmarble** [SamHH/bukubrow#63] opened 2018-09-25 16:19 UTC
I don't want to be rude but you really gotta have the README here explain the makefile a little better. I had no idea that:

A.) the `prepare-binaries` command in the makefile even existed
B.) that after running it I was then supposed to run ./install.sh in  the *.build* directory, not in binary

That was not at all intuitive even once I figured out I had to read the makefile. I just trusted the readme that all I would have to do is pretty much run ./binary/install.sh, as long as I had a good binary for linux (already in the repo, so good) and had the web extension already installed.

Personally I would break down the readme instructions into sections, the first  could be about the binaries--either use the ones in the repo or build them with `make <proper makefile command for building your binary>`

Then you can talk about the webextension--install it from the chrome or firefox store, or build it here (list the proper makefile command, I think `make webext`?) and then install it.

And then explicitly say what has to be done to actually install the binary so the web extension can use it, ie:

```
sudo make prepare-binaries
./.build/install.sh
```

And I think that'd help a lot of people I have to assume never used this because they didn't think to read the makefile when ./install.sh in the binary directory didn't work.

I don't think I'm alone in that I won't really go and check the makefile on my own, I'm just going to assume the readme will explain the only commands from it I care about as an end user.

---

Also this is a separate issue, but I think it's a poor choice to even have the build directory be a hidden directory. Why make it harder to find? What purpose does that serve? Yes most people can discover a hidden directory but I don't see the purpose in making it more difficult to find *the end result you actually want*.

**Comment by SamHH** [comment] 2018-09-26 10:15
I've never been particularly thrilled with the makefile setup here, and the README is clearly quite confusing for those unfamiliar with the project structure. I would like to improve it.

In response to some of the specific points raised:

> I had no idea that [...] the prepare-binaries command in the makefile even existed

You aren't really expected to run this command; I'm treating it essentially as a reusable function for the `binary-[platform]` commands. That's why it's not documented.

> I had no idea that [...] after running it I was then supposed to run ./install.sh in the .build directory, not in binary

This is fair, and I think someone else actually commented something similar in another issue a little while ago. How about if I changed the second binary installation step to specify running the script from the extracted package?

> Personally I would break down the readme instructions into sections, the first could be about the binaries--either use the ones in the repo or build them with make <proper makefile command for building your binary>

I think this is already covered with `Start out by downloading the latest binary [...or] refer to building.`, and in the building section, `Run make binary-linux-x64 (or substitute binary-linux-x64 for your preferred target) and then inside ./release you'll have a zip identical to what you would have downloaded as a binary in step 1.`.

The WebExtension is similarly covered.

> Also this is a separate issue, but I think it's a poor choice to even have the build directory be a hidden directory. Why make it harder to find? What purpose does that serve? Yes most people can discover a hidden directory but I don't see the purpose in making it more difficult to find the end result you actually want.

You're not supposed to ever interact with this directory yourself. The makefile commands to create a binary (`binary-[platform]` e.g. `make binary-linux-x64`) cover it from start to finish: creating the directory; copying the static files here in the appropriate structure; building the binary and placing it here; zipping everything up and moving that to the release dir; finally removing the directory and its contents.

**Comment by garfieldnate** [comment] 2018-11-24 21:39
I was going to open a new ticket but will comment here instead. I do not understand how to install this. I am on Mac OSX. 

The instructions say to download "the latest binary", but in the releases section there are only source distributions available so I download that instead. 

The instructions then say:

    Extract the package.
    Run ./install.sh to install the native messaging host. If you want a system-wide installation, run the script with sudo.

If you extract the package, there is no `./install.sh`. There is a "binary" package, so I assume that "binary/install.sh" is what should be run:

    $ binary/install.sh
    Select your browser:
    ====================
    1) Chrome
    2) Chromium
    3) Firefox
    1-3: 1

    Installing Chrome host config
    cp: /Users/nglenn/Downloads/bukubrow-ci_2018-09-24_b4bd2dc_osx/binary/chrome-host.json: No such file or directory

So the instructions didn't work for me. Like the previous commentor, I tried `make prepare-binary && ./.build/install.sh`, which did not print any errors. But the Chrome plugin does not work, and it shows this message in red: `The binary is outdated; please download or build a more recent one.`

I also tried running `make binary-darwin-x64`, but an error occurred while compiling `rusqlite`:

    error[E0599]: no method named `subsec_millis` found for type `std::time::Duration` in the current scope
      --> /Users/nglenn/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.14.0/src/busy.rs:26:49
       |
    26 |             .and_then(|t| t.checked_add(timeout.subsec_millis().into()))
       |                                                 ^^^^^^^^^^^^^

    error: aborting due to previous error

    error: Could not compile `rusqlite`.
    warning: build failed, waiting for other jobs to finish...
    error: build failed
    make: *** [binary-darwin-x64] Error 101

So now I'm stuck. I'm really excited to try this project, but I haven't been able to get it to work.

**Comment by SamHH** [comment] 2018-11-26 23:11
Hey @garfieldnate!

The lack of an up-to-date macOS binary is due to my failing to get CI up and running yet.

In the absence of a precompiled binary, you'll need to built it yourself. To do so, refer to the [Building](https://github.com/SamHH/bukubrow#building) segment of the README. The command you'll need in step 3 will be `binary-darwin-x64`.

**Comment by garfieldnate** [comment] 2018-11-28 20:35
Thanks for the help! The compile error was caused by an old rust version; just needed to `rustup update`.

**Comment by SamHH** [comment] 2019-01-25 13:56
Closing in favour of #79.

**Closed by SamHH** 2019-01-25 13:56 UTC
